-- Songs table (new schema)
create table if not exists public.songs (
  id bigint generated by default as identity not null,
  title text not null,
  album_id uuid not null,
  track_number integer not null,
  song_path text not null,
  uploader_id uuid not null,
  created_at timestamp with time zone null default now(),
  constraint songs_pkey primary key (id),
  constraint songs_album_id_fkey foreign key (album_id) references public.albums (id) on delete cascade,
  constraint songs_uploader_id_fkey foreign key (uploader_id) references public.users (id) on delete cascade
) tablespace pg_default;

-- Indexes
create index if not exists songs_album_id_idx on public.songs using btree (album_id);
create index if not exists songs_uploader_id_idx on public.songs using btree (uploader_id);
create index if not exists songs_title_trgm_idx on public.songs using gin (title gin_trgm_ops);

-- RLS
alter table public.songs enable row level security;

create policy "Songs are viewable by everyone"
  on public.songs for select
  using (true);

create policy "Authenticated users can insert songs"
  on public.songs for insert
  to authenticated
  with check (auth.uid() = uploader_id);

create policy "Users can update own songs"
  on public.songs for update
  to authenticated
  using (auth.uid() = uploader_id);

create policy "Users can delete own songs"
  on public.songs for delete
  to authenticated
  using (auth.uid() = uploader_id);