-- Table
create table public.songs (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  title text null,
  song_path text null,
  image_path text null,
  author text null,
  user_id uuid not null,
  constraint songs_pkey primary key (id),
  constraint songs_user_id_fkey foreign KEY (user_id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists songs_user_id_idx on public.songs using btree (user_id) TABLESPACE pg_default;

create index IF not exists songs_title_trgm_idx on public.songs using gin (title gin_trgm_ops) TABLESPACE pg_default;


-- Policies
alter policy "Enable insert for authenticated users only"
on "public"."songs"
to authenticated
with check (
  true
);

alter policy "Enable read access for all users"
on "public"."songs"
to public
using (
  true 
);